name: Deploy AWS-CDK Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
        - main
    paths:
        - '.github/workflows/infrastructure.yml'
        - 'SDESInfrastructure'

permissions:
  contents: read
  id-token: write

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest

    defaults:
        run:
            shell: bash
            working-directory: SDESInfrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: CDK Deploy
        run: npx cdk deploy --require-approval never
